### ISSUE TITLE
Reset global error options?

### ISSUE THREAD

**Issue by pgensler** [gaborcsardi/tamper#8]
Is there a way to reset the global error options after enabling this? How would you reset it to behave normally again?

**Comment by pgensler** [comment]
This code seems to trigger tamper's behavior, which is not what I want:
url = "https://www.ratebeer.com/beer/8802/"
site <- read_html(url)
x = html_nodes(site, #_brand4 span)

**Comment by gaborcsardi** [comment]
```
options(error = NULL)
```

Btw. that is syntactically invalid code.

**Comment by pgensler** [comment]
Gabe, I understand, the tag should be in quotes. Thanks for the quick response. Maybe add that option in the readme so users know how to disable it if needed?
